EXP:
  seed: 0
  env_name: 'LatteArtStir-v0'
SOLVER:
  n_iters: 5000
  init_range: 
    v: ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
    p: ((0.5, 0.73, 0.5), (0.5, 0.73, 0.5))
  optim:
    type: 'Adam'
    lr: 2e-4
    beta_1: 0.9
    beta_2: 0.99
