EXP:
  seed: 0
  env_name: 'Circulation-v0'
SOLVER:
  n_iters: 1000
  init_range: 
    v: ((0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02, 0.04), (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02, 0.04))
    p: ((0.55, 0.5, 0.35, 0.0, 0.0, 0.0, 0.0, 0.0), (0.55, 0.5, 0.35, 0.0, 0.0, 0.0, 0.0, 0.0))
  optim:
    type: 'Adam'
    lr: 5e-3
    beta_1: 0.9
    beta_2: 0.99
    bounds: (-1.0, 1.0)
